### ISSUE TITLE
Allow users to opt into tracks and show them the correct content for their track

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/onramp#39] opened 2019-08-26 10:32 UTC
- New to coding
- Frontend programmer
- WordPress programmer

**Comment by mattstauffer** [comment] 2019-10-24 02:28
We've built the tracks, but A) they're not fleshed out in the live content or the seeders and B) users can't opt in to which track they're using yet, so this isn't quite done yet.

**Comment by jonsugar** [comment] 2019-10-25 17:04
@mattstauffer I think this can be closed due to #24

**Comment by mattstauffer** [comment] 2019-10-25 17:44
I think we can just say that whatever closes #24 will also at least partially close this--but I want to make sure we consider actually *applying* the chosen track, which may not get done in the PR that closes #24. Thanks!

**Comment by TammyTee** [comment] 2020-03-06 16:39
This looks like a duplicate of #166 ? If so, PR #169 resolves this.

**Closed** 2020-03-06 18:20 UTC
Labels: enhancement, help wanted
