### ISSUE TITLE
Add a section on moving from WordPress to Laravel

### ISSUE THREAD

**Issue by Shelob9** [tightenco/onramp#21] opened 2019-07-27 21:20 UTC
I talked with @mattstauffer a bit at Laracon about adding a section for WordPress devs getting into Laravel. A lot of WordPress folks like myself are using more and more Laravel and it would be good to help translate some concepts from WordPress to Laravel to help.

Some ideas:

- WordPress vs MVC (https://tommcfarlin.com/wordpress-and-mvc/)
- Build a blog with Nova (https://nick-basile.com/blog/post/getting-started-with-laravel-nova)
- Laravel CMSes: Stamatic, Twil, etc.
- Routing, Controller and Blade vs themes and rewrite rules.
- Artisan vs WP-CLI
- Using Corcel to directly query WordPress data.
- Using the WordPress REST API to provide content to a Laravel app (I remember a post on this for Laravel News awhile ago.)
- Laravel Package equivelents -> Nova/ Advanced Custom Fields, Spark/ WooCommerce, etc.

I'll ask @twigpress if he has ideas about this.

**Comment by mattstauffer** [comment] 2019-07-29 23:29
Thanks @Shelob9! Duplicate of #17; would you mind add this as a content there, since I want to track this info coming from you? Thank you!!

**Closed by mattstauffer** 2019-07-29 23:29 UTC
